server:
#开头加/fosu
  servlet:
    context-path: /fosu
    
spring:
  #连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ''
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/school?characterEncoding=utf-8
    username: root
    #热部署
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true
      #json
  jackson:
    default-property-inclusion: non-default
  profiles:
    active: test

##默认密码为空
redis:
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      jedis:
        pool:
          #连接池最大连接数（使用负值表示没有限制）
          max-active: 100
          # 连接池中的最小空闲连接
          max-idle: 10
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: 100000
      # 连接超时时间（毫秒）
      timeout: 5000
      #默认是索引为0的数据库
      database: 0